# Agentic Spine AI Pipeline — Colab Training

This notebook **trains the vision engine** (the imaging model the agentic
pipeline's `VisionEngine` agent uses) on a free Colab GPU, saves the
checkpoints to your Google Drive for later use, downloads them to your PC,
and optionally fits **calibrated probabilities**.

**What it trains (multi-task):**
- Landmark localization — L1–L5 vertebrae + L1/L2…L5/S1 discs, per-point confidence
- Disc degeneration (DDD) Pfirrmann grade I..V — a multi-class softmax head
  (cross-entropy) trained when `ddd_labels.csv` is present

The full **agentic** layer (symptom agent, fusion agent, verification agent,
report agent) already works and calls Gemini — this notebook just gives the
pipeline its *eyes*.

**Before you start:** put the downloaded **SPIDER** dataset in Google Drive,
then run `prepare_spider.py` (cell 7) to build `coords_pretrain.csv` and
`ddd_labels.csv` and write the JPGs to `dataset/data/processed_spider_jpgs/`.

## 0. Edit these to your project

Put your GitHub repo URL below (or leave it and clone locally another way).

In [9]:
GITHUB_URL = 'https://github.com/codermisba/spinelit-ai.git'  # <-- EDIT: your repo

# Pull the Gemini key from the Colab Secrets panel (left sidebar > padlock
# icon > 'GEMINI_API_KEY'). Leave blank to skip LLM agents in Colab for now.
import os
GEMINI_KEY = "AIzaSyC0V8ZW-7TuBd_6M9fnnVRFVK1Yi4cxz4M"

# If the secrets panel var is named differently, set it explicitly here:
# GEMINI_KEY = ''
print('Repo:', GITHUB_URL)
print('Gemini key', 'SET (' + str(len(GEMINI_KEY)) + ' chars)' if GEMINI_KEY else 'NOT SET - agentic LLM steps will degrade')

Repo: https://github.com/codermisba/spinelit-ai.git
Gemini key SET (39 chars)


In [10]:
# 1. Check GPU - MUST show a GPU. Training on CPU will crash/timeout.
import torch
if not torch.cuda.is_available():
    raise SystemExit(
        'No GPU detected. Runtime > Change runtime type > GPU (T4) then '
        'Runtime > Restart session and re-run ALL cells from the top.'
    )
print('GPU available:')
!nvidia-smi -L
print()
print('PyTorch CUDA:', torch.version.cuda, '| GPU', torch.cuda.get_device_name(0))

GPU available:
GPU 0: Tesla T4 (UUID: GPU-dbf22384-37be-959d-c9db-176cd7610192)

PyTorch CUDA: 12.8 | GPU Tesla T4


In [11]:
# 2. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [12]:
# 3. Clone (or refresh) the repository
%cd /content
import os
GITHUB_URL = GITHUB_URL or 'https://github.com/codermisba/spinelit-ai.git'
if not os.path.exists('/content/spine-foundation'):
    !git clone {GITHUB_URL} spine-foundation
%cd /content/spine-foundation/
# Reset any stale local edits (e.g. a prior run overwrote config.py) then pull latest
!git checkout -- . 2>/dev/null; git pull || echo '(pull skipped/failed - see note)'
print('repo ready at /content/spine-foundation')

/content
/content/spine-foundation
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0 (from 0)
Unpacking objects: 100% (3/3), 893 bytes | 893.00 KiB/s, done.
From https://github.com/codermisba/spinelit-ai
   a79ec4e..1f913d6  main       -> origin/main
Updating a79ec4e..1f913d6
Fast-forward
 colab_training.ipynb | 23 +++++++++++++++++++----
 1 file changed, 19 insertions(+), 4 deletions(-)
repo ready at /content/spine-foundation


In [13]:
# 4. Install dependencies (PyTorch + CUDA GPU is preinstalled on Colab).
#    SimpleITK is required to read the SPIDER .mha volumes - without it
#    prepare_spider.py skips every case and the landmark CSVs are empty.
!pip install -q -r requirements.txt
import torch
print('PyTorch:', torch.__version__)
print('CUDA available:', torch.cuda.is_available())
print('GPU:', torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'N/A')
import SimpleITK
print('SimpleITK:', SimpleITK.__version__, '(OK - .mha volumes will load)')

PyTorch: 2.11.0+cu128
CUDA available: True
GPU: Tesla T4
SimpleITK: 2.5.6 (OK - .mha volumes will load)


In [14]:
# 5. Load the dataset from Google Drive (folder OR zip)
import os, shutil

DRIVE_ROOT = '/content/drive/MyDrive'
REPO_DATASET = '/content/spine-foundation/dataset'

# >>> EDIT if your folder lives somewhere else in Drive <<<
DATASET_DIR = f'{DRIVE_ROOT}/dataset'
DATASET_ZIP = f'{DRIVE_ROOT}/spine-foundation/dataset.zip'

def merge_copy(src, dst):
    # These are generated fresh by prepare_spider.py - never copy stale copies
    skip = {'coords_pretrain.csv','coords_vertebrae.csv','coords_rsna_improved.csv',
            'ddd_labels.csv','longitudinal_records.csv'}
    count = 0
    for root, _, files in os.walk(src):
        target = os.path.normpath(os.path.join(dst, os.path.relpath(root, src)))
        os.makedirs(target, exist_ok=True)
        for name in files:
            if name in skip:
                continue
            shutil.copy2(os.path.join(root, name), os.path.join(target, name))
            count += 1
    return count

if os.path.isdir(DATASET_DIR):
    print('Copying dataset folder from Drive...')
    print(f'  {merge_copy(DATASET_DIR, REPO_DATASET)} files copied.')
elif os.path.exists(DATASET_ZIP):
    !unzip -q -o "{DATASET_ZIP}" -d "{REPO_DATASET}"
    print('Unzipped dataset.zip')
else:
    print('Dataset not found at:', DATASET_DIR)
    !ls "{DRIVE_ROOT}"
    raise FileNotFoundError('Edit DATASET_DIR in this cell to point at your Drive folder.')

print('\nTop level of dataset/:')
!ls "{REPO_DATASET}"

Copying dataset folder from Drive...
  2475 files copied.

Top level of dataset/:
data


In [18]:
# 6a. Sanity check the dataset / model architecture.
#     The landmark CSVs must exist first - cell 7b (prepare_spider) creates
#     them. Until then this correctly skips instead of crashing.
import os
if os.path.exists('dataset/coords_pretrain.csv'):
    get_ipython().system('python dataset.py && echo --- && python model.py')
    print('\n>> dataset.py + model.py imported OK.')
else:
    print('dataset/coords_pretrain.csv not created yet - run cell 7b '
          '(prepare_spider.py) first, then re-run this cell.')

Dataset Size : 4
DDD labels available       : True

Image
torch.Size([3, 256, 256])

Coordinates
tensor([0.4836, 0.7487, 0.4397, 0.5749, 0.4303, 0.4588, 0.4529, 0.3422, 0.5093,
        0.2361, 0.4542, 0.6321, 0.4253, 0.5177, 0.4353, 0.3999, 0.4706, 0.2845,
        0.5481, 0.1876])

Point Visibility
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

DDD class (0-4) & mask
tensor([2, 2, 2, 1, 0])
tensor([1., 1., 1., 1., 0.])
---

model.safetensors: downloading bytes:  41% 46.9M/114M [00:00<00:00, 82.9MB/s, 1.86MB/s  ]
model.safetensors: reconstructing file:  43% 49.0M/114M [00:00<00:01, 50.8MB/s]
model.safetensors: downloading bytes:  80% 91.0M/114M [00:01<00:00, 132MB/s, 6.29MB/s  ] 
model.safetensors: downloading bytes: 100% 109M/109M [00:01<00:00, 86.9MB/s, 10.4MB/s  ]
model.safetensors: reconstructing file: 100% 114M/114M [00:01<00:00, 91.5MB/s, 11.0MB/s  ]

coords               (2, 20)
localization_conf    (2, 10)
ddd_logits           (2, 5, 5)
features             (2, 512)

>> datas

In [19]:
# 6b. Guard: the landmark CSVs MUST have real rows before training, or
#     train.py crashes with 'No columns to parse'. This fails loudly now.
import pandas as pd, os
for f in ['dataset/coords_pretrain.csv', 'dataset/ddd_labels.csv']:
    if not os.path.exists(f):
        print('NOT YET:', f, '- run cell 7 (prepare_spider) first.')
    else:
        n = len(pd.read_csv(f))
        ok = 'OK' if n > 0 else ('EMPTY - rerun cell 7 after fixing data!')
        print(f'{f}: {n} rows -> {ok}')

dataset/coords_pretrain.csv: 20 rows -> OK
dataset/ddd_labels.csv: 16 rows -> OK


## 7. Prepare the SPIDER dataset (DDD Pfirrmann labels)

Run `prepare_spider.py` on your downloaded **SPIDER** dataset. It selects the
midsagittal T2 slice + segmentation, derives the vertebral/disc centroids and
the DDD labels, and writes the JPGs. It produces:

- `dataset/coords_pretrain.csv` → columns `filename,level,relative_x,relative_y`
- `dataset/ddd_labels.csv` → columns `filename,level,pfirrmann_grade` (1–5)
```
filename,level,pfirrmann_grade
case_midsag.jpg,L3/L4,3
...
```

In [17]:
# 7b. RUN the SPIDER prep: builds coords_pretrain.csv + ddd_labels.csv + JPGs
# >>> EDIT --data_dir to point at your extracted SPIDER dataset <<<
!python prepare_spider.py --data_dir '/content/drive/MyDrive/SPIDER_data' --skip_download

# Fail loudly if the prep produced no landmark rows (never train on an empty CSV)
import os, pandas as pd
def rows(p):
    return 0 if not os.path.exists(p) else len(pd.read_csv(p))
land, grade = rows('dataset/coords_pretrain.csv'), rows('dataset/ddd_labels.csv')
print(f'Landmark rows: {land} | Pfirrmann rows: {grade}')
if land == 0:
    raise SystemExit('prepare_spider produced no landmark rows - stop here, fix --data_dir or the mask files, then re-run this cell.')

Radiology records : 1520
Image volumes     : 447
/content/spine-foundation/prepare_spider.py:196: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  Image.fromarray(arr8, mode="L").convert("RGB").save(jpg_out / fname)
/content/spine-foundation/prepare_spider.py:196: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  Image.fromarray(arr8, mode="L").convert("RGB").save(jpg_out / fname)
/content/spine-foundation/prepare_spider.py:196: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  Image.fromarray(arr8, mode="L").convert("RGB").save(jpg_out / fname)
/content/spine-foundation/prepare_spider.py:196: DeprecationWarning: 'mode' parameter is deprecated and will be removed in Pillow 13 (2026-10-15)
  Image.fromarray(arr8, mode="L").convert("RGB").save(jpg_out / fname)
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 0:
  #000: /tmp/SimpleITK-build/I

In [20]:
# 8. GPU-friendly settings (IMAGE_SIZE 512, bigger batch, more workers)
import re
cfg = open('config.py').read()
cfg = cfg.replace('IMAGE_SIZE = 256', 'IMAGE_SIZE = 512')
cfg = cfg.replace('BATCH_SIZE = 4', 'BATCH_SIZE = 32')
cfg = cfg.replace('NUM_WORKERS = 0', 'NUM_WORKERS = 2')
open('config.py','w').write(cfg)
print('Config updated for GPU training.')

# Optionally enable LLM agents inside this Colab (for live testing)
if GEMINI_KEY:
    import os
    os.environ['GEMINI_API_KEY'] = GEMINI_KEY
    open('/content/spine-foundation/.env','w').write('GEMINI_API_KEY=' + GEMINI_KEY + '\n')
    print('GEMINI_API_KEY set for Colab session.')

Config updated for GPU training.
GEMINI_API_KEY set for Colab session.


In [21]:
# 9. TRAIN the vision engine (checkpoints land in checkpoints/)
!python train.py --epochs 60


Loading Dataset...
Dataset Loaded  ->  Images : 4
DDD (Pfirrmann) labels available : True
Training tasks : localization + DDD (Pfirrmann)

Preparing Train / Validation Split...
Traceback (most recent call last):
  File "/content/spine-foundation/train.py", line 541, in <module>
    main()
    ~~~~^^
  File "/content/spine-foundation/train.py", line 537, in main
    trainer.fit()
    ~~~~~~~~~~~^^
  File "/content/spine-foundation/train.py", line 468, in fit
    self.prepare_dataloaders()
    ~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/content/spine-foundation/train.py", line 237, in prepare_dataloaders
    train_idx, val_idx = next(
                         ~~~~^
        splitter.split(self.dataset.image_names, labels)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/dist-packages/sklearn/model_selection/_split.py", line 1909, in split
    for train, test in self._iter_indices(X, y, groups):
                       ~~~~~~~~~~~~~~~~~~^^^^^^^

In [ ]:
# 10. Evaluate on the validation split
!python evaluate.py

## 11. Optional: fit calibrated probabilities

If you produced `ddd_labels.csv`, this fits an isotonic calibrator that maps
raw model confidence (Pfirrmann grade) to a **true probability (0–1)** — the
accuracy guarantee the agentic pipeline advertises. Saves
`checkpoints/calibration.pkl`.

In [ ]:
import os
if os.path.exists('dataset/ddd_labels.csv'):
    !python train_calibrator.py
else:
    print('No grading labels present -> using deterministic fallback calibration. '
          'Re-run after preparing ddd_labels.csv.')

## 12. Test the trained model through the agentic CLI

This runs the **real agentic pipeline** (vision + LLM agents). The reported
`agreement` / `calibrated probability` / verification reflect your trained model.
Set `GEMINI_KEY` in cell 0 to enable the LLM report; otherwise it degrades to the
numeric findings tables.

In [ ]:
import subprocess, glob
img = glob.glob('dataset/data/processed_spider_jpgs/*.jpg')
img = img[0] if img else glob.glob('dataset/data/**/*.jpg', recursive=True)[0]
print('testing image:', img)
!python cli_pipeline.py --image "{img}" --age 58 --sex female \
    --pain-scale 6 --modality mri --pain-years 4 --start-year 2022 \
    --symptoms "low back pain and numbness down the right leg" --pretty

## 13. Optional: launch the Gradio agentic UI inside Colab
First cell returns a public `*.gradio.live` link — keep it open to demo.

In [ ]:
!python app.py --share

## 14. SAVE everything to Google Drive (survives runtime reset)
Copies the trained model + calibrator into Drive so you never lose them.

In [ ]:
import shutil, os
DEST = '/content/drive/MyDrive/spine-checkpoints'
os.makedirs(DEST, exist_ok=True)
saved = []
for f in ['best_model.pth', 'last_model.pth', 'calibration.pkl', 'longitudinal_model.pth']:
    src = f'checkpoints/{f}'
    if os.path.exists(src):
        shutil.copy2(src, DEST)
        saved.append(f)
        print('saved', src, '->', DEST)
if not saved:
    print('No checkpoints found yet - run the TRAIN cell first.')
else:
    print('\nSafe in Drive:', DEST)
    print('To restore later anywhere: copy these files back into checkpoints/')

## 15. Download the trained model to your PC

Run this, choose the files in the popup, and save them into
`E:\spine-foundation\checkpoints\` on your Windows machine. Then your local
`app.py` / `cli_pipeline.py` will show real numbers.

In [ ]:
from google.colab import files
import os
to_download = [f for f in ['best_model.pth','calibration.pkl']
               if os.path.exists(f'checkpoints/{f}')]
if to_download:
    files.download('checkpoints/' + to_download[0])
    if len(to_download) > 1:
        files.download('checkpoints/' + to_download[1])
else:
    print('Nothing to download yet - train first.')

## 16. Restore checkpoints from Drive anytime

If your Colab runtime reset or you moved to a new notebook, run this to bring
your trained models back into `checkpoints/`.

```python
import shutil, os
SRC = '/content/drive/MyDrive/spine-checkpoints'
os.makedirs('/content/spine-foundation/checkpoints', exist_ok=True)
for f in ['best_model.pth','last_model.pth','calibration.pkl','longitudinal_model.pth']:
    s = os.path.join(SRC, f)
    if os.path.exists(s):
        shutil.copy2(s, '/content/spine-foundation/checkpoints/' + f)
        print('restored', f)
print('done')
```